name: GraffNet
options:
  minimumXcodeGenVersion: 2.41.0
packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk
    from: 10.0.0
targets:
  GraffNet:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: .
        excludes:
          - .github
          - project.yml
          - README.md
    info:
      properties:
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.fluxcode.streetgraf
    dependencies:
      - package: Firebase
        product: FirebaseAuth
      - package: Firebase
        product: FirebaseFirestore
      - package: Firebase
        product: FirebaseFirestoreSwift

