name: iOS Build

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install XcodeGen
        run: brew install xcodegen

      - name: Generate Xcode project
        run: xcodegen generate

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app

      - name: Build for iOS Simulator
        run: xcodebuild -scheme GraffNet -destination 'platform=iOS Simulator,name=iPhone 15' -configuration Debug -derivedDataPath build build

      - name: Upload simulator app artifact
        uses: actions/upload-artifact@v4
        with:
          name: GraffNet-Simulator-App
          path: build/Build/Products/Debug-iphonesimulator/GraffNet.app

